# Generated by Django 5.2.5 on 2025-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='uploads/docs/')),
                ('tenth', models.FileField(blank=True, null=True, upload_to='uploads/docs/')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('hobbies', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
